services:
  jekyll:
    image: amirpourmand/al-folio:latest
    build: .
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
    command: >
      sh -c "bundle install &&
             bundle exec jekyll serve --watch --force_polling --verbose -H 0.0.0.0 -P 8080"
